### PR TITLE
Add orientation option.

### PR DESCRIPTION
**Pull request by Choukk**

### CODE REVIEW

**Comment by deyvisonrocha** [comment]
hey guys, merge the implementation please! we need this!

**Comment by julihermes** [comment]
can you merge this, please? I need so much!

**Comment by clegginabox** [comment]
Sorry guys not sure how I missed the pull request.

Thanks for this choukk

**Comment by julihermes** [comment]
thanks for merge!!!

**Comment by deyvisonrocha** [comment]
Ok... on packagist this not updated yet!

**Comment by clegginabox** [comment]
It's updated now

**Comment by deyvisonrocha** [comment]
Thanks man! =)

**Pull request merged**
