### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by grigdodon**
Package itbz/fpdi is abandoned, you should avoid using it. Use setasign/fpdi instead.

### CODE REVIEW

**Review by didiergm — APPROVED** [review]

**Comment by ghost** [comment]
Could you please update it to setasign/fpdi? The old itbz/fpdi uses each() which is deprecated in PHP7.2

**Comment by OXRudy** [comment]
Please merge this.

**Comment by clegginabox** [comment]
Sorry for the delay, missed the email notifications

**Comment by rudzboy** [comment]
That was quick ! Thx regards

**Pull request merged**
